### PR TITLE
7pm-d - removed Search under Channels in the App Navbar and add app.google.search.apiToken

### PR DESCRIPTION
**Pull request by hunterlhxlin**
In this pr, I removed the Search navigator under Channels on the navbar, also added app.google.search.apiToken

### CODE REVIEW

**Comment by pconrad** [comment]
Needs a review from a fellow member of the team.

**Review by connorrapelje — COMMENTED** [review]
The changes look good.

**Review by yifanpan2023 — APPROVED** [review]
Looks great

**Review by christopherbarnett — APPROVED** [review]
very good, looks good to me

**Review by scottpchow23 — APPROVED** [review]

**Pull request merged**
