### PR TITLE
7pm c link to search page

### PR DESCRIPTION
**Pull request by Tom-Zu**
This is a separate issue from issue 20, but very similar. The main difference is that there is a clickable link on top of the page after log in that can direct you to the search page

### CODE REVIEW

**Review by DanielEskander — APPROVED** [review]
lgtm

**Review by pconrad — CHANGES_REQUESTED** [review]
Why does this PR have over 5000 changed files in it?

Something is very very wrong:

image

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
I'm merging this even without a code review from another team member because it is just a one line change and it's getting late.  Note however, that if a team member had done a peer review, you would have caught the 5000 files thing before I did :-)

**Comment by pconrad** [comment]
10 points awarded

**Comment by Tom-Zu** [comment]
Prof Conrad,

I think the reason it has 5000+ changes is because I created this branch off of main, not the 7pm-c-issue20 branch, so all the previous changes are considered new changes again, while the true difference between this and issue20 branch is just 4 to 5 lines of code

**Pull request merged**
