### PR TITLE
7pmc - Replaced Slack Ids with real names in the message display

### PR DESCRIPTION
**Pull request by levypik**
We replaced slack Id with real names on the message list component on the front end. For those slack users without real names, we left the slack id as is. 

Before: 

image

After: 

image

### CODE REVIEW

**Review by shouc — APPROVED** [review]

**Review by M1Lucken — APPROVED** [review]

**Comment by shouc** [comment]
I merged this to pr#64

**Comment by nicholasbrown1** [comment]
We updated this pull request to replace userIds within the message with real names.

**Review by pconrad — APPROVED** [review]
LGTM.... just testing the branch on Heroku prior to approving merging this into main

**Review by shouc — APPROVED** [review]
lgtm. merging it into #64 rn

**Comment by pconrad** [comment]
This is really nice.  I put in a follow up story for W21:

https://github.com/ucsb-cs156-f20/proj-mapache-search/issues/74

**Comment by pconrad** [comment]
40 points for this team

**Pull request merged**
