### PR TITLE
7pm-a-SearchMessages: Display a simple list of messages sent in Slack by the user that was searched

### PR DESCRIPTION
**Pull request by noas1019**
- As a user I can search all messages a particular user sent in a public slack channel so that I can easily locate a particular message
     - As a user I can click on the "AnalyzeMessageData" drop-down menu on the nav-bar then select 'Search Messages', where I can enter a full name (case/white space sensitive) and I am presented with a table of all their messages and the channel each message is in."
- add UserMessages/UserMessageList.js for table of messages
- implement SearchMessagesByUser.js to display simple list of messages of the searched user
- write frontend tests for SearchMessagesByUser
- add findByUser query in MessageRepository.java
- add "/usersearch" endpoint to MessageController.java
- add backend tests for api/members/messages/usersearch

### CODE REVIEW

**Review by andrewhlu — CHANGES_REQUESTED** [review]
Looks like your tests are failing, can you address them and re-request me for review?

**Comment by noas1019** [comment]
Tests pass now but not sure how to implement a mock backend for a fetch request for SearchMessagesByUser.js so the fetch request lines are uncovered.

**Comment by pconrad** [comment]
Try to fix the merge conflicts first, then I can try to help with the testing stuff

**Review by neenbeannnn — APPROVED** [review]

**Review by andrewhlu — CHANGES_REQUESTED** [review]
Some minor issues with the code. I wasn't able to test the changes on localhost or Heroku since I don't have the correct secrets to run the app, so I wasn't able to test the actual functionality of this change.

@pconrad When you get the chance, would you mind testing this on QA?

**Comment by pconrad** [comment]
Hi Everyone... could you address the changes that Andrew requested?

**Comment by phtcon** [comment]
Re adding the FIX ME label until the code reviewers have a chance to re-review and see if they are satisfied with the changes made.

**Comment by noas1019** [comment]
Hey Andrew I addressed all your code suggestions besides the last one (about creating a separate refactoring PR for white-space/factoring) because I was too scared to break something

**Review by neenbeannnn — APPROVED** [review]

**Comment by pconrad** [comment]
For this PR, the description is a list of what you did... which is helpful.

But what we need MORE than that, is a list of what this does from a USER standpoint, so that we can do the exploratory testing on the QA site.

Please add a sentence at the top with the user story, and what change this makes from a user perspective... i.e. which page of the app you go do, what you should do there, and what you should expect to see there:

**Comment by noas1019** [comment]
Hey Phil, I went ahead and update the description with more substance

**Comment by andrewhlu** [comment]
It looks like all the changes in the PR were duplicated in PR #80, which was merged yesterday. Can we close this PR?

**Pull request closed without merging**
